//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ Compatible
// This file is automatically generated by RisohEditor 5.7.8.
// Typaste_res.rc

#define IDS_README                          100
#define IDS_DELETESETTINGS                  101
#define IDS_TITLETEXT                       102

#define ID_EXIT                             100
#define ID_PROPERTIES                       101
#define ID_DELETE_SETTINGS                  102

#ifdef APSTUDIO_INVOKED
    #ifndef APSTUDIO_READONLY_SYMBOLS
        #define _APS_NO_MFC                 1
        #define _APS_NEXT_RESOURCE_VALUE    100
        #define _APS_NEXT_COMMAND_VALUE     103
        #define _APS_NEXT_CONTROL_VALUE     1000
        #define _APS_NEXT_SYMED_VALUE       300
    #endif
#endif
