#include "targetver.h"
#include <windows.h>
#include <windowsx.h>
#include <shellapi.h>
#include <shlwapi.h>
#include <commctrl.h>
#include <commdlg.h>
#include <string>
#include "AutoType.hpp"
#include "resource.h"
